version: "3"
services:
  server:
    build: .
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - mysqldb

  mysqldb:
    platform: linux/x86_64
    image: mysql
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: db_photovoltaic-system
      MYSQL_ROOT_PASSWORD: root