spring:
  application:
    name: Photovoltaic-System-Design
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  datasource:
    url: jdbc:mysql://mysqldb:3306/db_photovoltaic-system
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  output:
    ansi:
      enabled: ALWAYS
server:
  port: 8080
client:
  nrel:
    key: nrel-key
    url: http://nrel.base.url
  google:
    maps:
      credentials:
        key: google-maps-key
      url: http://google.maps.base.url
  viacep:
    url: http://via.cep.base.url